# Generated by Django 4.0.3 on 2022-06-01 09:13

import config.validation
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UsefulLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('title', models.CharField(blank=True, max_length=256, null=True, verbose_name='Sarlavha')),
                ('title_uz', models.CharField(blank=True, max_length=256, null=True, verbose_name='Sarlavha')),
                ('title_uzb', models.CharField(blank=True, max_length=256, null=True, verbose_name='Sarlavha')),
                ('title_ru', models.CharField(blank=True, max_length=256, null=True, verbose_name='Sarlavha')),
                ('title_en', models.CharField(blank=True, max_length=256, null=True, verbose_name='Sarlavha')),
                ('link', models.URLField(blank=True, max_length=500, null=True, verbose_name='Havola')),
                ('image', models.FileField(blank=True, null=True, upload_to='images/usefullink', validators=[config.validation.file_validation_exception], verbose_name='Rasm')),
                ('index', models.IntegerField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Foydali havola ',
                'verbose_name_plural': 'Foydali havolalar',
                'db_table': 'useful_link',
                'ordering': ['index'],
            },
        ),
    ]
