# Generated by Django 3.2.14 on 2022-07-05 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useful_link', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usefullink',
            name='index',
            field=models.IntegerField(blank=True, null=True, verbose_name='Indeks'),
        ),
    ]
