# Generated by Django 3.2.14 on 2022-08-03 07:08

import config.validation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useful_link', '0002_alter_usefullink_index'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usefullink',
            options={'ordering': ['index'], 'verbose_name': 'Фойдали ҳавола', 'verbose_name_plural': 'Фойдали ҳаволалар'},
        ),
        migrations.AlterField(
            model_name='usefullink',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='images/usefullink', validators=[config.validation.file_validation_exception], verbose_name='Расм'),
        ),
        migrations.AlterField(
            model_name='usefullink',
            name='index',
            field=models.IntegerField(blank=True, null=True, verbose_name='Индекс'),
        ),
        migrations.AlterField(
            model_name='usefullink',
            name='link',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Ҳавола'),
        ),
        migrations.AlterField(
            model_name='usefullink',
            name='title',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Сарлавҳа'),
        ),
        migrations.AlterField(
            model_name='usefullink',
            name='title_en',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Сарлавҳа'),
        ),
        migrations.AlterField(
            model_name='usefullink',
            name='title_ru',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Сарлавҳа'),
        ),
        migrations.AlterField(
            model_name='usefullink',
            name='title_uz',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Сарлавҳа'),
        ),
        migrations.AlterField(
            model_name='usefullink',
            name='title_uzb',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Сарлавҳа'),
        ),
    ]
