# Generated by Django 3.2.13 on 2022-06-02 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibit',
            name='audio',
            field=models.FileField(blank=True, upload_to='exhibit/audios/', verbose_name='Audio: '),
        ),
        migrations.AddField(
            model_name='exhibit',
            name='audio_en',
            field=models.FileField(blank=True, null=True, upload_to='exhibit/audios/', verbose_name='Audio: '),
        ),
        migrations.AddField(
            model_name='exhibit',
            name='audio_ru',
            field=models.FileField(blank=True, null=True, upload_to='exhibit/audios/', verbose_name='Audio: '),
        ),
        migrations.AddField(
            model_name='exhibit',
            name='audio_uz',
            field=models.FileField(blank=True, null=True, upload_to='exhibit/audios/', verbose_name='Audio: '),
        ),
        migrations.AddField(
            model_name='exhibit',
            name='audio_uzb',
            field=models.FileField(blank=True, null=True, upload_to='exhibit/audios/', verbose_name='Audio: '),
        ),
    ]
