# Generated by Django 4.0.3 on 2022-06-08 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibit', '0004_alter_category_created_by_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibit',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='Asosiy'),
        ),
    ]
