# Generated by Django 4.0.3 on 2022-06-09 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exhibit', '0005_exhibit_is_main'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exhibit',
            old_name='invented',
            new_name='invented_year',
        ),
        migrations.RenameField(
            model_name='exhibit',
            old_name='used',
            new_name='used_years',
        ),
        migrations.RenameField(
            model_name='exhibit',
            old_name='used_en',
            new_name='used_years_en',
        ),
        migrations.RenameField(
            model_name='exhibit',
            old_name='used_ru',
            new_name='used_years_ru',
        ),
        migrations.RenameField(
            model_name='exhibit',
            old_name='used_uz',
            new_name='used_years_uz',
        ),
        migrations.RenameField(
            model_name='exhibit',
            old_name='used_uzb',
            new_name='used_years_uzb',
        ),
    ]
