# Generated by Django 3.2.13 on 2022-06-10 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibit', '0006_rename_invented_exhibit_invented_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='exhibit/logos/', verbose_name='Logotip: '),
        ),
    ]
