# Generated by Django 4.0.3 on 2022-06-13 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibit', '0007_alter_category_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibit',
            name='evolution',
            field=models.BooleanField(default=False, verbose_name='Evolutsiya'),
        ),
    ]
