# Generated by Django 4.0.3 on 2022-06-15 09:07

import config.validation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibit', '0008_exhibit_evolution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='exhibit/logos/', validators=[config.validation.file_validation_exception], verbose_name='Logotip: '),
        ),
    ]
