# Generated by Django 4.0.3 on 2022-06-21 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibit', '0009_alter_category_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exhibit',
            name='evolution',
        ),
        migrations.RemoveField(
            model_name='exhibit',
            name='is_main',
        ),
        migrations.AddField(
            model_name='category',
            name='index',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Tartib raqami'),
        ),
        migrations.AddField(
            model_name='category',
            name='to_main_page',
            field=models.BooleanField(default=False, verbose_name='Bosh sahifa'),
        ),
        migrations.AddField(
            model_name='exhibit',
            name='to_about_page',
            field=models.BooleanField(default=False, verbose_name='Muzey haqida'),
        ),
        migrations.AddField(
            model_name='exhibit',
            name='to_main_page',
            field=models.BooleanField(default=False, verbose_name='Bosh sahifa'),
        ),
    ]
