# Generated by Django 3.2.13 on 2022-06-23 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibit', '0011_alter_category_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exhibit',
            options={'ordering': ('created_at',), 'verbose_name': 'Eksponat', 'verbose_name_plural': 'Eksponatlar'},
        ),
        migrations.AlterField(
            model_name='exhibit',
            name='invented_year',
            field=models.CharField(max_length=4, verbose_name='Ixtiro yili: '),
        ),
        migrations.AlterField(
            model_name='exhibit',
            name='used_years',
            field=models.CharField(max_length=100, verbose_name='Foydalanilgan davri: '),
        ),
        migrations.AlterField(
            model_name='exhibit',
            name='used_years_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Foydalanilgan davri: '),
        ),
        migrations.AlterField(
            model_name='exhibit',
            name='used_years_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Foydalanilgan davri: '),
        ),
        migrations.AlterField(
            model_name='exhibit',
            name='used_years_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='Foydalanilgan davri: '),
        ),
        migrations.AlterField(
            model_name='exhibit',
            name='used_years_uzb',
            field=models.CharField(max_length=100, null=True, verbose_name='Foydalanilgan davri: '),
        ),
    ]
