# Generated by Django 3.2.13 on 2022-06-28 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibit', '0013_alter_exhibit_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibit',
            name='gif',
            field=models.ImageField(blank=True, null=True, upload_to='exhibit/gifs/', verbose_name='Gif'),
        ),
    ]
