# Generated by Django 3.2.14 on 2022-07-08 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibit', '0014_exhibit_gif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibit',
            name='summary',
            field=models.TextField(max_length=2500, verbose_name='Qisqacha: '),
        ),
        migrations.AlterField(
            model_name='exhibit',
            name='summary_en',
            field=models.TextField(max_length=2500, null=True, verbose_name='Qisqacha: '),
        ),
        migrations.AlterField(
            model_name='exhibit',
            name='summary_ru',
            field=models.TextField(max_length=2500, null=True, verbose_name='Qisqacha: '),
        ),
        migrations.AlterField(
            model_name='exhibit',
            name='summary_uz',
            field=models.TextField(max_length=2500, null=True, verbose_name='Qisqacha: '),
        ),
        migrations.AlterField(
            model_name='exhibit',
            name='summary_uzb',
            field=models.TextField(max_length=2500, null=True, verbose_name='Qisqacha: '),
        ),
    ]
