# Generated by Django 3.2.14 on 2022-07-08 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exhibit', '0015_auto_20220708_0543'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exhibit',
            options={'ordering': ('invented_year',), 'verbose_name': 'Eksponat', 'verbose_name_plural': 'Eksponatlar'},
        ),
    ]
