# Generated by Django 3.2.14 on 2022-08-03 07:08

import config.utils
import config.validation
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exhibit', '0016_alter_exhibit_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('index',), 'verbose_name': 'Категория', 'verbose_name_plural': 'Категориялар'},
        ),
        migrations.AlterModelOptions(
            name='exhibit',
            options={'ordering': ('invented_year',), 'verbose_name': 'Экспонат', 'verbose_name_plural': 'Экспонатлар'},
        ),
        migrations.AlterModelOptions(
            name='exhibitimages',
            options={'verbose_name': 'Расм', 'verbose_name_plural': 'Расмлар'},
        ),
        migrations.AlterField(
            model_name='category',
            name='index',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Тартиб рақами'),
        ),
        migrations.AlterField(
            model_name='category',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='exhibit/logos/', validators=[config.validation.file_validation_exception], verbose_name='Логотип: '),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Номи:'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Номи:'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Номи:'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_uz',
            field=models.CharField(max_length=200, null=True, verbose_name='Номи:'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_uzb',
            field=models.CharField(max_length=200, null=True, verbose_name='Номи:'),
        ),
        migrations.AlterField(
            model_name='category',
            name='to_main_page',
            field=models.BooleanField(default=False, verbose_name='Бош саҳифа'),
        ),
        migrations.AlterField(
            model_name='exhibit',
            name='audio',
            field=models.FileField(blank=True, upload_to='exhibit/audios/', validators=[config.utils.validate_file_extension], verbose_name='Аудио: '),
        ),
        migrations.AlterField(
            model_name='exhibit',
            name='audio_en',
            field=models.FileField(blank=True, null=True, upload_to='exhibit/audios/', validators=[config.utils.validate_file_extension], verbose_name='Аудио: '),
        ),
        migrations.AlterField(
            model_name='exhibit',
            name='audio_ru',
            field=models.FileField(blank=True, null=True, upload_to='exhibit/audios/', validators=[config.utils.validate_file_extension], verbose_name='Аудио: '),
        ),
        migrations.AlterField(
            model_name='exhibit',
            name='audio_uz',
            field=models.FileField(blank=True, null=True, upload_to='exhibit/audios/', validators=[config.utils.validate_file_extension], verbose_name='Аудио: '),
        ),
        migrations.AlterField(
            model_name='exhibit',
            name='audio_uzb',
            field=models.FileField(blank=True, null=True, upload_to='exhibit/audios/', validators=[config.utils.validate_file_extension], verbose_name='Аудио: '),
        ),
        migrations.AlterField(
            model_name='exhibit',
            name='body',
            field=models.TextField(verbose_name='Экспонат ҳақида: '),
        ),
        migrations.AlterField(
            model_name='exhibit',
            name='body_en',
            field=models.TextField(null=True, verbose_name='Экспонат ҳақида: '),
        ),
        migrations.AlterField(
            model_name='exhibit',
            name='body_ru',
            field=models.TextField(null=True, verbose_name='Экспонат ҳақида: '),
        ),
        migrations.AlterField(
            model_name='exhibit',
            name='body_uz',
            field=models.TextField(null=True, verbose_name='Экспонат ҳақида: '),
        ),
        migrations.AlterField(
            model_name='exhibit',
            name='body_uzb',
            field=models.TextField(null=True, verbose_name='Экспонат ҳақида: '),
        ),
        migrations.AlterField(
            model_name='exhibit',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='exhibit.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='exhibit',
            name='cover',
            field=models.ImageField(upload_to='exhibit/images/', verbose_name='Расм'),
        ),
        migrations.AlterField(
            model_name='exhibit',
            name='invented_year',
            field=models.CharField(max_length=4, verbose_name='Ихтиро йили: '),
        ),
        migrations.AlterField(
            model_name='exhibit',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Номи: '),
        ),
        migrations.AlterField(
            model_name='exhibit',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Номи: '),
        ),
        migrations.AlterField(
            model_name='exhibit',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Номи: '),
        ),
        migrations.AlterField(
            model_name='exhibit',
            name='name_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Номи: '),
        ),
        migrations.AlterField(
            model_name='exhibit',
            name='name_uzb',
            field=models.CharField(max_length=255, null=True, verbose_name='Номи: '),
        ),
        migrations.AlterField(
            model_name='exhibit',
            name='summary',
            field=models.TextField(max_length=2500, verbose_name='Қисқача: '),
        ),
        migrations.AlterField(
            model_name='exhibit',
            name='summary_en',
            field=models.TextField(max_length=2500, null=True, verbose_name='Қисқача: '),
        ),
        migrations.AlterField(
            model_name='exhibit',
            name='summary_ru',
            field=models.TextField(max_length=2500, null=True, verbose_name='Қисқача: '),
        ),
        migrations.AlterField(
            model_name='exhibit',
            name='summary_uz',
            field=models.TextField(max_length=2500, null=True, verbose_name='Қисқача: '),
        ),
        migrations.AlterField(
            model_name='exhibit',
            name='summary_uzb',
            field=models.TextField(max_length=2500, null=True, verbose_name='Қисқача: '),
        ),
        migrations.AlterField(
            model_name='exhibit',
            name='to_about_page',
            field=models.BooleanField(default=False, verbose_name='Музей ҳақида'),
        ),
        migrations.AlterField(
            model_name='exhibit',
            name='to_main_page',
            field=models.BooleanField(default=False, verbose_name='Бош саҳифа'),
        ),
        migrations.AlterField(
            model_name='exhibit',
            name='used_years',
            field=models.CharField(max_length=100, verbose_name='Фойдаланилган даври: '),
        ),
        migrations.AlterField(
            model_name='exhibit',
            name='used_years_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Фойдаланилган даври: '),
        ),
        migrations.AlterField(
            model_name='exhibit',
            name='used_years_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Фойдаланилган даври: '),
        ),
        migrations.AlterField(
            model_name='exhibit',
            name='used_years_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='Фойдаланилган даври: '),
        ),
        migrations.AlterField(
            model_name='exhibit',
            name='used_years_uzb',
            field=models.CharField(max_length=100, null=True, verbose_name='Фойдаланилган даври: '),
        ),
        migrations.AlterField(
            model_name='exhibitimages',
            name='exhibit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='exhibit.exhibit', verbose_name='Экспонат: '),
        ),
        migrations.AlterField(
            model_name='exhibitimages',
            name='image',
            field=models.ImageField(upload_to='exhibit/images/', verbose_name='Расм: '),
        ),
    ]
