# Generated by Django 4.0.3 on 2022-05-31 10:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('title', models.CharField(max_length=500, verbose_name='Sarlavha')),
                ('title_uz', models.CharField(max_length=500, null=True, verbose_name='Sarlavha')),
                ('title_uzb', models.CharField(max_length=500, null=True, verbose_name='Sarlavha')),
                ('title_ru', models.CharField(max_length=500, null=True, verbose_name='Sarlavha')),
                ('title_en', models.CharField(max_length=500, null=True, verbose_name='Sarlavha')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Matni')),
                ('content_uz', models.TextField(blank=True, null=True, verbose_name='Matni')),
                ('content_uzb', models.TextField(blank=True, null=True, verbose_name='Matni')),
                ('content_ru', models.TextField(blank=True, null=True, verbose_name='Matni')),
                ('content_en', models.TextField(blank=True, null=True, verbose_name='Matni')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='news', verbose_name='Asosiy rasm')),
                ('views', models.IntegerField(blank=True, default=0, null=True, verbose_name="Ko'rishlar Soni")),
                ('pub_date', models.DateField(default=django.utils.timezone.now, verbose_name='Sanasi')),
                ('on_slider', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Yangilik',
                'verbose_name_plural': 'Yangiliklar',
                'db_table': 'news',
                'ordering': ['-pub_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='NewsImages', verbose_name='Foto')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('index', models.IntegerField(blank=True, null=True, verbose_name='Tartib raqami')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='news.news', verbose_name='Rasmlar')),
            ],
            options={
                'db_table': 'news_images',
                'ordering': ['index'],
            },
        ),
    ]
