# Generated by Django 3.2.14 on 2022-08-03 07:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_news_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-pub_date', '-created_at'], 'verbose_name': 'Янгилик', 'verbose_name_plural': 'Янгиликлар'},
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Матни'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content_en',
            field=models.TextField(blank=True, null=True, verbose_name='Матни'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Матни'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Матни'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content_uzb',
            field=models.TextField(blank=True, null=True, verbose_name='Матни'),
        ),
        migrations.AlterField(
            model_name='news',
            name='photo',
            field=models.ImageField(upload_to='news', verbose_name='Асосий расм'),
        ),
        migrations.AlterField(
            model_name='news',
            name='pub_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Санаси'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=500, verbose_name='Сарлавҳа'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title_en',
            field=models.CharField(max_length=500, null=True, verbose_name='Сарлавҳа'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title_ru',
            field=models.CharField(max_length=500, null=True, verbose_name='Сарлавҳа'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title_uz',
            field=models.CharField(max_length=500, null=True, verbose_name='Сарлавҳа'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title_uzb',
            field=models.CharField(max_length=500, null=True, verbose_name='Сарлавҳа'),
        ),
        migrations.AlterField(
            model_name='news',
            name='views',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Кўришлар Сони'),
        ),
        migrations.AlterField(
            model_name='newsimages',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='NewsImages', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='newsimages',
            name='index',
            field=models.IntegerField(blank=True, null=True, verbose_name='Тартиб рақами'),
        ),
        migrations.AlterField(
            model_name='newsimages',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Актив'),
        ),
        migrations.AlterField(
            model_name='newsimages',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='news.news', verbose_name='Расмлар'),
        ),
    ]
