# Generated by Django 4.0.3 on 2022-05-31 10:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoGallery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('title', models.CharField(max_length=500, verbose_name='Galereya nomi')),
                ('title_uz', models.CharField(max_length=500, null=True, verbose_name='Galereya nomi')),
                ('title_uzb', models.CharField(max_length=500, null=True, verbose_name='Galereya nomi')),
                ('title_ru', models.CharField(max_length=500, null=True, verbose_name='Galereya nomi')),
                ('title_en', models.CharField(max_length=500, null=True, verbose_name='Galereya nomi')),
                ('photo', models.ImageField(upload_to='images', verbose_name='Asosiy rasm')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Foto galereya',
                'verbose_name_plural': 'Foto galereya',
                'db_table': 'photo_gallery',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='PhotoGalleryImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='PhotoGallery/', verbose_name='Rasm')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='gallery.photogallery', verbose_name='Tasvirlar')),
            ],
            options={
                'db_table': 'photo_gallery_images',
            },
        ),
    ]
