# Generated by Django 3.2.13 on 2022-07-04 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_employee_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['index'], 'verbose_name': 'Hodim', 'verbose_name_plural': 'Hodimlar'},
        ),
    ]
