# Generated by Django 3.2.14 on 2022-07-05 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_alter_employee_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['index'], 'verbose_name': 'Xodim', 'verbose_name_plural': 'Xodimlar'},
        ),
    ]
