# Generated by Django 3.2.14 on 2022-08-03 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_alter_employee_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['index'], 'verbose_name': 'Ходим', 'verbose_name_plural': 'Ходимлар'},
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Электрон почта'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='index',
            field=models.IntegerField(blank=True, null=True, verbose_name='Тартиб рақами'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='is_lidership',
            field=models.BooleanField(default=False, verbose_name='Раҳбарият'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Тўлиқ Исм'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name_en',
            field=models.CharField(max_length=500, null=True, verbose_name='Тўлиқ Исм'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name_ru',
            field=models.CharField(max_length=500, null=True, verbose_name='Тўлиқ Исм'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name_uz',
            field=models.CharField(max_length=500, null=True, verbose_name='Тўлиқ Исм'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name_uzb',
            field=models.CharField(max_length=500, null=True, verbose_name='Тўлиқ Исм'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(max_length=30, verbose_name='Телефон рақам'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='EmployeeImages', verbose_name='Расм'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(max_length=500, verbose_name='Лавозим'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position_en',
            field=models.CharField(max_length=500, null=True, verbose_name='Лавозим'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position_ru',
            field=models.CharField(max_length=500, null=True, verbose_name='Лавозим'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position_uz',
            field=models.CharField(max_length=500, null=True, verbose_name='Лавозим'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position_uzb',
            field=models.CharField(max_length=500, null=True, verbose_name='Лавозим'),
        ),
    ]
