# Generated by Django 3.2.13 on 2022-06-17 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, verbose_name='Manzil')),
                ('transport', models.CharField(max_length=255, verbose_name='Transport')),
                ('phone', models.CharField(max_length=125, verbose_name='Telefon')),
                ('email', models.EmailField(max_length=254)),
                ('work_time', models.CharField(max_length=255, verbose_name='Ish vaqtlari')),
                ('landmark', models.CharField(max_length=255, verbose_name="Mo'ljal")),
            ],
            options={
                'verbose_name': "Bog'lanish",
                'verbose_name_plural': "Bog'lanish",
                'db_table': 'contact',
            },
        ),
        migrations.CreateModel(
            name='LandmarkPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='ContactPhotos', verbose_name='Rasm')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='contact.contact')),
            ],
            options={
                'verbose_name': 'Moljal rasmi',
                'verbose_name_plural': "Mo'ljal rasmlari",
                'db_table': 'landmark_photos',
            },
        ),
    ]
