# Generated by Django 3.2.13 on 2022-06-21 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='landmark',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='work_time',
        ),
        migrations.AddField(
            model_name='landmarkphotos',
            name='landmark',
            field=models.CharField(default='', max_length=255, verbose_name="Mo'ljal"),
        ),
    ]
