# Generated by Django 3.2.13 on 2022-06-21 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20220621_1144'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='landmarkphotos',
            options={'ordering': ('id',), 'verbose_name': 'Moljal rasmi', 'verbose_name_plural': "Mo'ljal rasmlari"},
        ),
        migrations.RenameField(
            model_name='landmarkphotos',
            old_name='landmark',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='landmarkphotos',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landmarks', to='contact.contact'),
        ),
    ]
