# Generated by Django 3.2.13 on 2022-06-23 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_auto_20220621_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='address_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Manzil'),
        ),
        migrations.AddField(
            model_name='contact',
            name='address_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Manzil'),
        ),
        migrations.AddField(
            model_name='contact',
            name='address_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Manzil'),
        ),
        migrations.AddField(
            model_name='contact',
            name='address_uzb',
            field=models.CharField(max_length=255, null=True, verbose_name='Manzil'),
        ),
        migrations.AddField(
            model_name='contact',
            name='transport_en',
            field=models.TextField(max_length=255, null=True, verbose_name='Transport'),
        ),
        migrations.AddField(
            model_name='contact',
            name='transport_ru',
            field=models.TextField(max_length=255, null=True, verbose_name='Transport'),
        ),
        migrations.AddField(
            model_name='contact',
            name='transport_uz',
            field=models.TextField(max_length=255, null=True, verbose_name='Transport'),
        ),
        migrations.AddField(
            model_name='contact',
            name='transport_uzb',
            field=models.TextField(max_length=255, null=True, verbose_name='Transport'),
        ),
        migrations.AddField(
            model_name='landmarkphotos',
            name='name_en',
            field=models.CharField(default='', max_length=255, null=True, verbose_name="Mo'ljal"),
        ),
        migrations.AddField(
            model_name='landmarkphotos',
            name='name_ru',
            field=models.CharField(default='', max_length=255, null=True, verbose_name="Mo'ljal"),
        ),
        migrations.AddField(
            model_name='landmarkphotos',
            name='name_uz',
            field=models.CharField(default='', max_length=255, null=True, verbose_name="Mo'ljal"),
        ),
        migrations.AddField(
            model_name='landmarkphotos',
            name='name_uzb',
            field=models.CharField(default='', max_length=255, null=True, verbose_name="Mo'ljal"),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.TextField(verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='transport',
            field=models.TextField(max_length=255, verbose_name='Transport'),
        ),
    ]
