# Generated by Django 3.2.14 on 2022-08-03 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_alter_contact_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Боғланиш', 'verbose_name_plural': 'Боғланиш'},
        ),
        migrations.AlterModelOptions(
            name='landmarkphotos',
            options={'ordering': ('id',), 'verbose_name': 'Мўлжал расми', 'verbose_name_plural': 'Мўлжал расмлари'},
        ),
        migrations.AlterField(
            model_name='contact',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Манзил'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='address_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Манзил'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='address_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Манзил'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='address_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Манзил'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='address_uzb',
            field=models.CharField(max_length=255, null=True, verbose_name='Манзил'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.TextField(verbose_name='Email почта'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.TextField(verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='transport',
            field=models.TextField(max_length=255, verbose_name='Транспорт'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='transport_en',
            field=models.TextField(max_length=255, null=True, verbose_name='Транспорт'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='transport_ru',
            field=models.TextField(max_length=255, null=True, verbose_name='Транспорт'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='transport_uz',
            field=models.TextField(max_length=255, null=True, verbose_name='Транспорт'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='transport_uzb',
            field=models.TextField(max_length=255, null=True, verbose_name='Транспорт'),
        ),
        migrations.AlterField(
            model_name='landmarkphotos',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='Мўлжал'),
        ),
        migrations.AlterField(
            model_name='landmarkphotos',
            name='name_en',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='Мўлжал'),
        ),
        migrations.AlterField(
            model_name='landmarkphotos',
            name='name_ru',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='Мўлжал'),
        ),
        migrations.AlterField(
            model_name='landmarkphotos',
            name='name_uz',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='Мўлжал'),
        ),
        migrations.AlterField(
            model_name='landmarkphotos',
            name='name_uzb',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='Мўлжал'),
        ),
        migrations.AlterField(
            model_name='landmarkphotos',
            name='photo',
            field=models.ImageField(upload_to='ContactPhotos', verbose_name='Расм'),
        ),
    ]
