# Generated by Django 3.2.14 on 2022-08-03 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Фойдаланувчи', 'verbose_name_plural': 'Фойдаланувчилар'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='firstname',
            field=models.CharField(max_length=100, verbose_name='Исм'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='lastname',
            field=models.CharField(max_length=100, verbose_name='Фамилия'),
        ),
    ]
