# Generated by Django 4.0.3 on 2022-06-10 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='photo',
            field=models.ImageField(upload_to='events', verbose_name='Asosiy rasm'),
        ),
    ]
