# Generated by Django 3.2.14 on 2022-08-03 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_auto_20220728_1110'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-start_time'], 'verbose_name': 'Тадбир', 'verbose_name_plural': 'Тадбирлар'},
        ),
        migrations.AlterModelOptions(
            name='eventimages',
            options={'verbose_name': 'Тадбир Расм', 'verbose_name_plural': 'Тадбир Расмлар'},
        ),
        migrations.AlterModelOptions(
            name='eventtype',
            options={'ordering': ['title'], 'verbose_name': 'Тадбир тури', 'verbose_name_plural': 'Тадбир турлари'},
        ),
        migrations.AlterField(
            model_name='event',
            name='content',
            field=models.TextField(verbose_name='Матн'),
        ),
        migrations.AlterField(
            model_name='event',
            name='content_en',
            field=models.TextField(null=True, verbose_name='Матн'),
        ),
        migrations.AlterField(
            model_name='event',
            name='content_ru',
            field=models.TextField(null=True, verbose_name='Матн'),
        ),
        migrations.AlterField(
            model_name='event',
            name='content_uz',
            field=models.TextField(null=True, verbose_name='Матн'),
        ),
        migrations.AlterField(
            model_name='event',
            name='content_uzb',
            field=models.TextField(null=True, verbose_name='Матн'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.DateTimeField(verbose_name='Тугаш вақти'),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Актив'),
        ),
        migrations.AlterField(
            model_name='event',
            name='num_visitors',
            field=models.IntegerField(default=0, verbose_name='Ташриф буюрувчилар сони'),
        ),
        migrations.AlterField(
            model_name='event',
            name='photo',
            field=models.ImageField(upload_to='events', verbose_name='Асосий расм'),
        ),
        migrations.AlterField(
            model_name='event',
            name='pub_date',
            field=models.DateField(blank=True, null=True, verbose_name='Эълон Санаси'),
        ),
        migrations.AlterField(
            model_name='event',
            name='responsible_org',
            field=models.CharField(max_length=255, verbose_name='Масъул ташкилот'),
        ),
        migrations.AlterField(
            model_name='event',
            name='responsible_org_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Масъул ташкилот'),
        ),
        migrations.AlterField(
            model_name='event',
            name='responsible_org_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Масъул ташкилот'),
        ),
        migrations.AlterField(
            model_name='event',
            name='responsible_org_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Масъул ташкилот'),
        ),
        migrations.AlterField(
            model_name='event',
            name='responsible_org_uzb',
            field=models.CharField(max_length=255, null=True, verbose_name='Масъул ташкилот'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(verbose_name='Бошланиш вақти'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Мавзу'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Мавзу'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Мавзу'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Мавзу'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title_uzb',
            field=models.CharField(max_length=255, null=True, verbose_name='Мавзу'),
        ),
        migrations.AlterField(
            model_name='event',
            name='views',
            field=models.IntegerField(default=0, verbose_name='Кўришлар сони'),
        ),
        migrations.AlterField(
            model_name='eventimages',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='EventImages', verbose_name='Расм'),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='title',
            field=models.CharField(max_length=256, verbose_name='Номи'),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='title_en',
            field=models.CharField(max_length=256, null=True, verbose_name='Номи'),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='title_ru',
            field=models.CharField(max_length=256, null=True, verbose_name='Номи'),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='title_uz',
            field=models.CharField(max_length=256, null=True, verbose_name='Номи'),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='title_uzb',
            field=models.CharField(max_length=256, null=True, verbose_name='Номи'),
        ),
    ]
