# Generated by Django 3.2.14 on 2022-08-03 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'Музей тарихи', 'verbose_name_plural': 'Музей тарихи'},
        ),
    ]
