# Generated by Django 3.2.14 on 2022-08-10 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_alter_about_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Биз ҳақимизда'),
        ),
        migrations.AlterField(
            model_name='about',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Биз ҳақимизда'),
        ),
        migrations.AlterField(
            model_name='about',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Биз ҳақимизда'),
        ),
        migrations.AlterField(
            model_name='about',
            name='description_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Биз ҳақимизда'),
        ),
        migrations.AlterField(
            model_name='about',
            name='description_uzb',
            field=models.TextField(blank=True, null=True, verbose_name='Биз ҳақимизда'),
        ),
        migrations.AlterField(
            model_name='aboutimages',
            name='about',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='about.about', verbose_name='Расмлар'),
        ),
        migrations.AlterField(
            model_name='aboutimages',
            name='image',
            field=models.ImageField(blank=True, upload_to='AboutImages', verbose_name='Фото'),
        ),
    ]
