# Generated by Django 4.0.3 on 2022-06-10 07:29

import config.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Karusel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=510, verbose_name='Mavzu')),
                ('title_uz', models.CharField(max_length=510, null=True, verbose_name='Mavzu')),
                ('title_uzb', models.CharField(max_length=510, null=True, verbose_name='Mavzu')),
                ('title_ru', models.CharField(max_length=510, null=True, verbose_name='Mavzu')),
                ('title_en', models.CharField(max_length=510, null=True, verbose_name='Mavzu')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Karusel mavzusi',
                'verbose_name_plural': 'Karusel mavzulari',
            },
        ),
        migrations.CreateModel(
            name='KaruselImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='KoruselImages', validators=[config.utils.validate_file_extension], verbose_name='Rasmlar')),
                ('karusel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='karusel.karusel')),
            ],
            options={
                'verbose_name': 'Karusel rasmi',
                'verbose_name_plural': 'Karusel rasmlari',
            },
        ),
    ]
