# Generated by Django 4.0.3 on 2022-06-10 11:54

import config.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karusel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karuselimages',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='KoruselImages', validators=[config.utils.imagefile_validation_exception], verbose_name='Rasmlar'),
        ),
        migrations.AlterModelTable(
            name='karusel',
            table='karusel',
        ),
        migrations.AlterModelTable(
            name='karuselimages',
            table='karusel_images',
        ),
    ]
