# Generated by Django 4.0.3 on 2022-06-12 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('karusel', '0002_alter_karuselimages_image_alter_karusel_table_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='karusel',
            name='slug',
        ),
        migrations.AlterField(
            model_name='karuselimages',
            name='karusel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='karusel.karusel'),
        ),
    ]
