# Generated by Django 3.2.13 on 2022-06-17 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('karusel', '0003_remove_karusel_slug_alter_karuselimages_karusel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='karusel',
            options={'verbose_name': 'Bosh sahifa mavzusi', 'verbose_name_plural': 'Bosh sahifa mavzusi'},
        ),
    ]
