# Generated by Django 3.2.13 on 2022-06-21 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karusel', '0004_alter_karusel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karusel',
            name='title',
            field=models.TextField(verbose_name='Mavzu'),
        ),
        migrations.AlterField(
            model_name='karusel',
            name='title_en',
            field=models.TextField(null=True, verbose_name='Mavzu'),
        ),
        migrations.AlterField(
            model_name='karusel',
            name='title_ru',
            field=models.TextField(null=True, verbose_name='Mavzu'),
        ),
        migrations.AlterField(
            model_name='karusel',
            name='title_uz',
            field=models.TextField(null=True, verbose_name='Mavzu'),
        ),
        migrations.AlterField(
            model_name='karusel',
            name='title_uzb',
            field=models.TextField(null=True, verbose_name='Mavzu'),
        ),
    ]
