# Generated by Django 4.0.3 on 2022-06-02 06:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcursionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Nomlanishi')),
                ('name_uz', models.CharField(max_length=500, null=True, verbose_name='Nomlanishi')),
                ('name_uzb', models.CharField(max_length=500, null=True, verbose_name='Nomlanishi')),
                ('name_ru', models.CharField(max_length=500, null=True, verbose_name='Nomlanishi')),
                ('name_en', models.CharField(max_length=500, null=True, verbose_name='Nomlanishi')),
            ],
            options={
                'verbose_name': 'Ekskursiya turi',
                'verbose_name_plural': 'Ekskursiya turlari',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('firstname', models.CharField(max_length=254, verbose_name='Ism')),
                ('firstname_uz', models.CharField(max_length=254, null=True, verbose_name='Ism')),
                ('firstname_uzb', models.CharField(max_length=254, null=True, verbose_name='Ism')),
                ('firstname_ru', models.CharField(max_length=254, null=True, verbose_name='Ism')),
                ('firstname_en', models.CharField(max_length=254, null=True, verbose_name='Ism')),
                ('lastname', models.CharField(max_length=254, verbose_name='Familiyasi')),
                ('lastname_uz', models.CharField(max_length=254, null=True, verbose_name='Familiyasi')),
                ('lastname_uzb', models.CharField(max_length=254, null=True, verbose_name='Familiyasi')),
                ('lastname_ru', models.CharField(max_length=254, null=True, verbose_name='Familiyasi')),
                ('lastname_en', models.CharField(max_length=254, null=True, verbose_name='Familiyasi')),
                ('email', models.EmailField(max_length=254, verbose_name='Elektron pochtasi')),
                ('phone', models.CharField(max_length=15, verbose_name='Telefon raqami')),
                ('visit_time', models.DateTimeField(auto_now=True, verbose_name='Tashrif vaqti')),
                ('num_visitors', models.IntegerField(default=0, verbose_name='Tashrif buyuruvchilar soni')),
                ('organization', models.CharField(max_length=500, verbose_name='Muassasa nomi')),
                ('organization_uz', models.CharField(max_length=500, null=True, verbose_name='Muassasa nomi')),
                ('organization_uzb', models.CharField(max_length=500, null=True, verbose_name='Muassasa nomi')),
                ('organization_ru', models.CharField(max_length=500, null=True, verbose_name='Muassasa nomi')),
                ('organization_en', models.CharField(max_length=500, null=True, verbose_name='Muassasa nomi')),
                ('excursion_lan', models.CharField(choices=[['uz', "O'zbekcha"], ['ru', 'Ruscha'], ['en', 'Inglizcha']], max_length=254, verbose_name='Ekskursiya tili')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('excursion_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.excursiontype', verbose_name='Ekskursiya turi')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'On-line buyurtma',
                'verbose_name_plural': 'On-line buyurtmalar',
                'ordering': ['visit_time'],
            },
        ),
    ]
