# Generated by Django 4.0.3 on 2022-06-02 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='num_visitors',
            field=models.IntegerField(default=0, verbose_name='Tashrifchilar soni'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=15, verbose_name="Bog'lanish telefoni"),
        ),
        migrations.AlterField(
            model_name='order',
            name='visit_time',
            field=models.DateTimeField(auto_now=True, verbose_name='Tashrif kuni va soati'),
        ),
    ]
