# Generated by Django 4.0.3 on 2022-06-02 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_num_visitors_alter_order_phone_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='excursiontype',
            table='excursion_type',
        ),
        migrations.AlterModelTable(
            name='order',
            table='order',
        ),
    ]
