# Generated by Django 3.2.13 on 2022-06-29 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_order_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='reason',
            field=models.TextField(blank=True, null=True, verbose_name='Rad etish sababi'),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Yangi'), (2, 'Qabul qilindi'), (3, 'Rad etildi')], default=1, verbose_name='Status'),
        ),
    ]
